# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Liberating Structures
tagline:          'INCLUDING AND UNLEASHING EVERYONE'
description:      ''
url:              
baseurl:          /ls

author:
  name:           'Sage Vann'
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/sagevann/ls